goplus/spx

- game.go
change screenshot key var name from Capture to ScreenshotKey
> change screenshot key var name from Capture to ScreenshotKey

- internal/anim/animapi.go
- sprite.go
fix anim stops two , crash bugs
> fix anim stops two , crash bugs  and turnto shortest path

- dir.go
- dir_js.go
- internal/gdi/font/font_canvas.go
- internal/gdi/gdi_canvas.go
1. fix build --tags canvas
2. skip setupWorkDir on js
> fix run for wasm

- say.go
- test/Bananas/Red.spx
Roll back the position of "say", should check it through the camera
> Roll back the position of "say", should check it through the camera

- internal/svgr/svg.go
cache the svg to image,which could decrease cpu usage
> cache the svg 

- go.mod
- internal/gdi/font/font.go
> internal/gdi/font: font cache use io.ReaderAt

- config.go
- game.go
- spbase.go
- sprite.go
- test/Bananas/assets/index.json
- test/Bullet/assets/index.json
- test/Camera/assets/index.json
- test/CameraTouching/assets/index.json
- test/Dinosaur/assets/index.json
- test/Hello/assets/index.json
- test/Measure/assets/index.json
- test/MiniMapCamera/res/index.json
- test/MonkeyAndCrocodile/res/index.json
- test/Reloadable/res/ch-1.json
- test/StageMonitor/res/index.json
- test/TurnHeading/res/index.json
- test/TurnToMouse/res/index.json
- test/_Quote/res/index.json
- tutorial/01-Weather/assets/index.json
- tutorial/01-Weather/assets/sprites/Jaime/index.json
- tutorial/01-Weather/assets/sprites/Kai/index.json
- tutorial/02-Dragon/assets/index.json
- tutorial/03-Clone/assets/index.json
- tutorial/04-Bullet/assets/index.json
- tutorial/05-Animation/assets/index.json
builder#456 -5 rename scene(index) property : stage costume / scene -> backdrop
> builder#456 -5 rename scene(index) property

- event.go
- game.go
- test/Bullet/assets/index.json
SceneName -> BackdropName
SceneIndex -> BackdropIndex
StartScene -> SetBackdrop
NextScene -> NextBackdrop
PrevScene -> PrevBackdrop
OnScene -> OnBackdrop
> rename spx api from scene => backdrop

- config.go
- internal/anim/anim.go
- internal/anim/animapi.go
- sprite.go
https://github.com/goplus/builder/issues/604
Adjust sound-playing behavior for animation:
Sound playing starts together with the animation
If animation is played repeatedly, the sound is played repeatedly with the same cycle time
https://github.com/goplus/spx/assets/8347962/c5d7d03f-cb88-4f91-976c-7d4157f4bfec
> #builder #604 adjust sound-playing behavior for animation

- sprite.go
> animation binding: support "step"

- game.go
- internal/gdi/gdi_canvas.go
- monitor.go
1. panic if not found widget
2. monitor support SetSize
3. fix wasm build with tags canvas
https://github.com/goplus/builder/issues/648
[Builder#648_fix.zip](https://github.com/user-attachments/files/16621624/Builder.648_fix.zip)
https://github.com/user-attachments/assets/ee9103ee-eb37-4a35-bafd-8f8af5f7b1ac
> Builder#648 fix widget

- sprite.go
glide anim, do not convert vector2 to float
> fix: Sprite Glide panics #319

- sprite.go
Fix custume set anim duration bug
example:
```
cd test/_Quote
spx run .
```
> Fix custume set anim duration bug#349

- game.go
Fixed the bug with the left button click event (single click triggering multiple times)
test:
```
cd test/_Quote
spx run .
```
> Fixed left button click event bug: trigger mutil times

- sprite.go
- test/_Quote/res/sprites/Crocodile/index.json
Fixed step animation bug & fixed _Quote config error(not keep last frame )
test:
```
cd test/_Quote
spx run .
```
> Fixed step animation bug 

- cmd/spx/go.mod
- cmd/spx/template/go.mod.txt
- game.go
- gdspx.go
- go.mod
- go.sum
- internal/engine/engine.go
- internal/engine/proxy.go
Add keyboard event
test:
```
cd test/_Quote
spx run .
```
> Add keyboard event issue#349

- cmd/spx/go.mod
- cmd/spx/main.go
- cmd/spx/template/go.mod.txt
- cmd/spx/template/index.html
- go.mod
https://github.com/goplus/spx/issues/349 
Add spx cmd clearbuild & exportspx & runspx , use browser's cache to run the game
ps: only works on the Windows platform, untested on other platforms.
> Web res interperter mode issue#349

- game.go
- internal/ui/ui_measure.go
- internal/ui/ui_monitor.go
- internal/ui/ui_quote.go
- internal/ui/ui_say.go
- internal/ui/util.go
Fixed ui anchor pos error
test:
```
cd tutorial/01-Weather
spx runweb
```
> Fix ui anchor pos error issue#349

- game.go
- internal/engine/sync.go
Fix backdrop render scale error
test:
```
cd tutorial/01-Weather
spx run .
```
> Fix backdrop render scale error : issue#349

- game.go
Fix the panic when bind audio on start (web platform)
test: [audio_bind_web.zip](https://github.com/user-attachments/files/17520352/audio_bind_panic_web.zip)
> Fix the panic when bind audio on start (web platform)#349

- camera.go
- cmd/spx/main.go
- internal/ui/ui_say.go
- quote.go
- say.go
- spbase.go
- sprite.go
Fix sprite's Bound function, as well as the TODO related to "Bound" function
test:
```
cd test/_Quote
spx run .
```
> Fix sprite's Bound function, as well as the TODO related to "Bound" function issue#349

- spgdi.go
test:[my-test.zip](https://github.com/user-attachments/files/17541574/my-test.zip)
> Fix: calculate the position of TrackPos based on the non-transparent area

- cmd/spx/main.go
- cmd/spx/template/game.js
- cmd/spx/template/index.html
- cmd/spx/template/runner.html
Adapt the runner interface to be consistent with ispx
> Adapt the runner interface to be consistent with ispx

- cmd/spx/template/game.js
> Remove service worker

- cmd/spx/template/game.js
- cmd/spx/template/runner.html
Add a setting "isEditor" to switch between editor mode and game mode
> Add a setting to switch between editor mode and game mode

- cmd/spx/template/game.js
- cmd/spx/template/index.html
- cmd/spx/template/runner.html
https://github.com/user-attachments/assets/6860c31f-d0d1-4b47-9b8d-824160c3dd18
runner.html adds more APIs to better control the editor cache
``` js
// load project at backgound 
window.startProject(buffer, isEditor = false, projectName = "Game")
// update project asset
window.updateProject(buffer, addInfos, deleteInfos, updateInfos)
// start a game base on the current project asset
window.runGame()
// stop the game
window.stopGame() 
```
> Web editor cache mode, Update project by zip (& diff info) (Add,Delete,Update)

- cmd/spx/template/game.js
- cmd/spx/template/index.html
- cmd/spx/template/runner.html
Update runner's api : all public interfaces return a "Promise" to increase usability https://github.com/goplus/spx/issues/349
Please refer to :  **"cmd/spx/template/index.html"**
project link (the zip file is too big to upload to github)：https://pan.baidu.com/s/1F38MG_Ewe8tglCnK4ChW0g?pwd=73qq 
1. download and unzip it
2. run the script (run.bat or run.sh)
```
./run.sh 8163
```
https://github.com/user-attachments/assets/1a27ca3c-e927-43fc-a94d-5b3b24531c9a
> Update runner's api : all public interfaces return a "Promise" to increase usability#issue349

- cmd/spx/template/game.js
Fix runner task dependency
reply on the new gdspx event 'update_project' ,  pr: https://github.com/realdream-ai/godot/pull/5
> Fix runner task dependency

- cmd/spx/template/game.js
- cmd/spx/template/runner.html
Cache the project's zip file and hash to improve loading speed
> Cache the project's zip file and hash to improve loading speed

- cmd/spx/template/game.js
- cmd/spx/template/index.html
- cmd/spx/template/runner.html
Add stop project function:
```js
window.stopProject = async () => {
...
}
```
> Add stop project function

- sprite.go
fixed issue : https://github.com/goplus/spx/issues/386 
Test project:
[10-WebTestProj.zip](https://github.com/user-attachments/files/17699187/10-WebTestProj.zip)
raw:
current:
> Fix sprite's render scale（apply sprite's scale）

- gdspx.go
- say.go
- sprite.go
Fix ui's offset of `say` or `think`
> Fix ui's offset of `say` or `think`

- cmd/spx/main.go
- cmd/spx/template/game.js
- cmd/spx/template/index.html
fix: https://github.com/goplus/spx/issues/402
Add a function to wait for `cache synchronization` to complete, ensuring that `startGame` runs only after `updateProject` has finished.
https://github.com/user-attachments/assets/cbfeee5b-7a21-48a5-96d4-3050804e4eae
> Add a function to wait for cache synchronization to complete

- cmd/spx/template/game.js
- cmd/spx/template/runner.html
Automatically stop the previous project, if it exists, when starting a new one
> Automatically stop the previous project, if it exists, when starting a new one

- .gitignore
- init.sh
> Add init script

- internal/engine/sync.go
- internal/ui/ui_monitor.go
- monitor.go
> Fix monitor visibility

- gdspx.go
fix: https://github.com/goplus/spx/issues/446
test project: [17-AlphaBound.zip](https://github.com/user-attachments/files/17841059/17-AlphaBound.zip)
> Fix RotationStyle `LeftRight`

- cmd/spx/main.go
Automatically generate engineres.zip package when exporting web resources
> Automatically generate engineres.zip package when exporting web resources

- cmd/ispx/go.mod
- cmd/ispx/go.sum
- cmd/spx/go.mod
- cmd/spx/go.sum
- cmd/spx/main.go
- cmd/spx/template/project/.builds/web/game.js
- cmd/spx/template/project/.builds/web/runner.html
- cmd/spx/template/project/.godot/gdspx_web_server.py
- cmd/spx/template/project/go.mod.txt
- go.mod
- go.sum
Add web editor direct load mode (no need to import resource)
Related  pr:  https://github.com/realdream-ai/godot/pull/23
Test project: [05-Animation.zip](https://github.com/user-attachments/files/17912242/05-Animation.zip)
https://github.com/user-attachments/assets/80a1a311-37cf-4652-b7b8-9205ae56fccb
> Editor direct mode web

- cmd/ispx/go.mod
- cmd/ispx/go.sum
- cmd/spx/go.mod
- cmd/spx/go.sum
- cmd/spx/template/project/go.mod.txt
- go.mod
- go.sum
- internal/engine/engine.go
- internal/engine/sync.gen.go
- internal/time/time.go
```
func Frame() int64 
func TimeScale() float64 
func SetTimeScale(value float64) 
func DeltaTime() float64 
func UnscaledDeltaTime() float64 
func RealTimeSinceStartup() float64 
func TimeSinceLevelLoad() float64 
```
> Add time util

- camera.go
- event.go
- game.go
- monitor.go
- spbase.go
- sprite.go
- widget.go
Merge main branch pr: https://github.com/goplus/spx/pull/463
- Introduce `SpriteName`, `SpriteCostumeName`, `SpriteAnimationName`, `SoundName`, `BackdropName`, `WidgetName`.
- Prefer func overloading over using `interface{}` or variadic params as optional params.
> Merge main: refactor: prefer typed params for API funcs (#463) 

- internal/coroutine/coro.go
- internal/coroutine/queue.go
full implement of : https://github.com/goplus/spx/issues/443
1. Increase the priority of MainThreadCall
2. Blocking the current coroutine to wait for the main thread call to complete
3. Optimize the implementation of the queue by using a linked list instead of an array
> Blocking the current coroutine to wait for the main thread call to complete

- internal/anim/anim.go
- sprite.go
fix https://github.com/goplus/spx/issues/485
> Fix wrong frames when play step animation

- game.go
- sprite.go
Add timeout detection in the For loop of the Main function to prevent the main loop from getting stuck.
> Add timeout detection in the For loop of the Main function

- camera.go
- config.go
- game.go
- gdspx.go
- tutorial/05-Animation/assets/index.json
test project: [windowscale.zip](https://github.com/user-attachments/files/19243422/windowscale.zip)
config: assets/index.json
```
{
"windowScale":2,
...
}
```
eg: 
default: windowScale==1
windowScale==2
> Support window scale

- game.go
- gdspx.go
- internal/coroutine/coro.go
- sprite.go
Add timeout detection in the For loop of the Main function to prevent the main loop from getting stuck. (#494)  (#520)
test project: [test.zip](https://github.com/user-attachments/files/19386712/test.zip)
> Add timeout detection in the For loop of the Main function to prevent the main loop from getting stuck. (#494)(#520)

- game.go
issue: https://github.com/goplus/spx/issues/539
test project: [06_WaitUtil.zip](https://github.com/user-attachments/files/19440466/06_WaitUtil.zip)
eg:
```go
var (
startToSay bool
)
onStart => {
startToSay = false
waitUtil => startToSay
say "Hello, Calf!", 3
}
onMsg "sayhello", => {
startToSay = true
}
```
> Add WaitUtil

- audio.go
- game.go
- internal/engine/engine.go
- internal/enginewrap/sync.gen.go
- internal/enginewrap/sync_pure.gen.go
- sprite.go
issue: https://github.com/goplus/spx/issues/508
test project: [07-sound.zip](https://github.com/user-attachments/files/19549938/07-sound.zip)
test demo script:
```go
import "math"
onStart => {
say "Calf1 Pitch 100" 
setSoundEffect SoundPitchEffect, 100
play "sfx", true
wait 1
say "Calf1 Pitch 150"
setSoundEffect SoundPitchEffect, 150
play "sfx", true
wait 1
say "Calf1 Pitch 50"
setSoundEffect SoundPitchEffect, 50
play "sfx", true
broadcast "testpan"
setSoundEffect SoundPitchEffect, 100
wait 2
say "play music "
play "music", false
}
```
```go
onMsg "testpan", => {
wait 1
say "Calf2 left"
setSoundEffect SoundPanEffect, -100
play "sfx", true
wait 2
say "Calf2 right"
setSoundEffect SoundPanEffect, 100
play "sfx", true
wait 2
say "Calf2 normal"
setSoundEffect SoundPanEffect, 0
play "sfx", true …
```
> Add Sound effect

- spbase.go
- sprite.go
- Fix backrop setcostume
- Fix glide data type error : value => pointer
> Fix little bugs

- game.go
- internal/coroutine/coro.go
- internal/debug/debug.go
issue: https://github.com/goplus/spx/issues/561
how to test:
```sh
git clone https://github.com/JiepengTan/spx2_test_demos demos
cd demos/AircraftWar
spx run .
```
demo:
https://github.com/user-attachments/assets/38097066-1223-40bf-9f00-e3406bfbf3a3
> Fix bugs of demo01-AirCraft

- game.go
- internal/engine/platform/const.go
> On mobile platforms, automatically adapt the resolution to achieve a fullscreen effect

- game.go
how to test:
`git clone https://github.com/JiepengTan/spx2_test_demos demos
cd demos/BetaGo
spx run .`
> bug: Full screen click cannot be detected in main

- game.go
- internal/ui/ui_ask.go
- internal/ui/ui_measure.go
- internal/ui/ui_monitor.go
- internal/ui/ui_quote.go
- internal/ui/ui_say.go
- internal/ui/util.go
todolist: https://github.com/goplus/spx/issues/498
test project: [match3.zip](https://github.com/user-attachments/files/19755654/match3.zip)
issue: https://github.com/goplus/spx/issues/577
> Adapt ui's pos and scale to support windowScale

- sprite.go
issue: https://github.com/goplus/spx/issues/579
todolist: https://github.com/goplus/spx/issues/498
test project: [match3.zip](https://github.com/user-attachments/files/19755654/match3.zip)
> Do not call the engine interface to play animation when there is no animation data

- game.go
> Fix typo error of answer

- sprite.go
issues:https://github.com/goplus/spx/issues/594
> fix setsize bug

- cmd/gox/pkg/command/args.go
- config.go
- game.go
1. Modify the project configuration (index.json)
```json
{
"fullScreen": true,
...
"zorder": [
]
}
```
2. Run spx with the -fullscreen argument
eg: spx run -fullscreen
https://github.com/user-attachments/assets/4a5d40f7-bdaf-42ab-933c-df47fa926779
> Support fullscreen

- cmd/igox/pkg/github.com/goplus/spx/export.go
- sprite.go
test project: [test.zip](https://github.com/user-attachments/files/20179873/test.zip)
`type specialDir = int` => `type Direction = float64`
test code 
``` go
onStart => {
say "Hello Go+"
wait 1
turn 60
wait 1
turn 60.0
wait 1
turnTo 180
wait 1
turnTo 90.0
wait 1
}
```
> Rename specialDir => Direction（int => float64）

- camera.go
- cmd/igox/main.go
- config.go
- event.go
- game.go
- input.go
- internal/coroutine/coro.go
- internal/engine/sprite.go
- internal/engine/sync.go
- internal/engine/util.go
- internal/tools/reflections/reflections.go
- internal/tools/tool.go
- list.go
- measure.go
- pkg/gdspx/internal/webffi/callbacks.gen.go
- pkg/gdspx/internal/webffi/ffi.go
- pkg/gdspx/internal/webffi/util.go
- say.go
- spbase.go
- sprite.go
issue: https://github.com/goplus/spx/issues/638
> Replace interface{} to any in public api

- internal/enginewrap/sync.gen.go
- internal/enginewrap/sync_pure.gen.go
- pkg/gdspx/internal/ffi/ffi.gen.go
- pkg/gdspx/internal/ffi/ffi_wrapper.gen.go
- pkg/gdspx/internal/ffi/ffi_wrapper.gen.h
- pkg/gdspx/internal/ffi/gdextension_spx_ext.h
- pkg/gdspx/internal/webffi/ffi.gen.go
- pkg/gdspx/internal/wrap/manager_wrapper.gen.go
- pkg/gdspx/internal/wrap/manager_wrapper_web.gen.go
- pkg/gdspx/pkg/engine/interface.gen.go
- pkg/gdspx/pkg/engine/sprite.gen.go
- pkg/gdspx/pkg/engine/sprite_pure.gen.go
- spbase.go
issue: https://github.com/goplus/spx/issues/647
test project: [test.zip](https://github.com/user-attachments/files/20299811/test.zip)
> Temp fix SetMaterialParamsVec4 bug

- cmd/igox/pkg/github.com/goplus/spx/export.go
- game.go
- spbase.go
- sprite.go
- test/All/SpEffect.spx
- test/All/SpLook.spx
- test/Bananas/Monkey.spx
issue: https://github.com/goplus/spx/issues/654
> Fix typo error

- sprite.go
issue: https://github.com/goplus/spx/issues/649
test project: [test.zip](https://github.com/user-attachments/files/20320727/test.zip)
test script:
```
onTouchStart ["Dragon", "aa"], =>{
println("aaa")
}
```
> Merget 483

- sprite.go
issue: https://github.com/goplus/spx/issues/649
> Update sprite interface

- cmd/gox/pkg/command/env.go
- Fix android build project name error
- Clear .temp dir
> Update cmd tools

- cmd/igox/main.go
- gop.mod
> fix(cmd/igox): inline import `math` package for spx

- .github/workflows/release.yml
- cmd/igox/build.sh
- pkg/gdspx/tools/build_engine.sh
Automatically generate release packages for the spx2 project during builds and deliver them to the builder
> Add spx2 CD

- game.go
- say.go
- sprite.go
> refactor: improve param naming consistency in Ask methods

- cmd/gox/pkg/command/build.go
- cmd/gox/pkg/command/export.go
- cmd/gox/template/project/.gitignore.txt
- event.go
- game.go
- input.go
test project:  [test.zip](https://github.com/user-attachments/files/21273093/test.zip)
main.spx
```go
onStart => {
println("onStart stage ")
}
onSwipe Left, => {
println "onSwipe left stage"
}
```
calf.spx
```go
onStart => {
say "Hello Go+"
}
onSwipe Left, => {
say "onSwipe left "+name
println "onSwipe left ",name
}
onSwipe Right, => {
say "onSwipe right "+name
println "onSwipe right ",name
}
```
https://github.com/user-attachments/assets/90bf439a-de84-49dc-ab69-5699dcae95c5
> Feat: add input gesture swipe
