config.go
game.go

"map":   {    "width": 1000,    "height": 2000,    "mode": "repeat"  },
"map":   {    "width": 800,    "height": 400,    "mode": "fillRatio"  },
"map":   {    "width": 400 ,    "height": 800,    "mode": "fillRatio"  },

builder#459 fixed Stage mode: repeat & fillRatio

---

audio.go
game.go
sprite.go

[builder#443 Simplify process to add & play sound](https://github.com/goplus/builder/issues/443)

builder#443 Simplify process to add & play sound

---

config.go
internal/math32/vector2.go
spgdi.go
sprite.go

https://github.com/goplus/builder/issues/570
https://github.com/goplus/spx/assets/8347962/48143d4d-f12d-43a6-a080-5a8ec553d39b

#builder#570 sprite pivot

---

spgdi.go

https://github.com/goplus/spx/issues/293

fix #293 sprite's pivot should be scaled by current costume's bitmapResolution

---

game.go
internal/gdi/text/draw.go
monitor.go
widget.go

https://github.com/goplus/builder/issues/648
[Project file 648.zip](https://github.com/user-attachments/files/16373580/648.zip)
https://github.com/user-attachments/assets/d00657f8-e9dc-42af-812c-e8bdea67ab45
PS: The issues with font scaling and position adaptation will be resolved after the upgrade of the font library to EbitenEngine or Godot. Currently, go+builder can disable the Monitor's scaling feature to circumvent this bug.

Builder#648 support Widget Monitor

---

game.go
monitor.go

1. convert the "GetWidget" function to a generic function  https://github.com/goplus/spx/pull/306#discussion_r1713095270
```
monitor := getWidget(Monitor,"life")
```
2. add default values for the 'size' and 'color' attributes of the Monitor https://github.com/goplus/spx/pull/306#discussion_r1705019171
3. make the coordinate concept of Widget consistent with sprite, where 0,0 represents the center of the screen, and the y-axis points upwards https://github.com/goplus/spx/pull/306#discussion_r1706601813 https://github.com/goplus/spx/pull/306#discussion_r1706616273
[Project : 648_generic.zip](https://github.com/user-attachments/files/16622490/648_generic.zip)

Builder#648  Convert the "GetWidget" function to a generic function

---

game.go
sprite.go

Update https://github.com/goplus/builder/issues/765
We simplified function body of `Gopt_Game_Gopx_GetWidget` in this PR to make it easy for ispx to support generics. See detials in https://github.com/goplus/builder/issues/765#issuecomment-2313915805
Related change in Builder: https://github.com/goplus/builder/pull/767

Support ispx with generics

---

sprite.go

reset default costume index after the sprite initialized.
no need to switch behaviour of playDefaultAnimation in sprite.go.

fix: Initial costumeIndex for sprite not working #317

---

sprite.go

Unify Die behavior of initial / cloned sprite https://github.com/goplus/spx/issues/314
This fix is temporary. It's better to switch to the prefab/instance workflow like unity.

fix: Unify Die behavior of initial / cloned sprite #314

---

event.go
game.go
sprite.go
tutorial/05-Animation/Bullet.spx
tutorial/05-Animation/SmallEnemy.spx

Add lifecycle of touch behaviour, like touchBegin, touched, touchEnd;
Add DbgFlagPerf flag of game, monitoring performance like collision detection in each frame;
Changed the old usage of Touching(something),
(1) if the parameter is a name of a sprite, no life cycle of touching is triggered.
(2) for the other cases, such as edge or mouse parameters, the usage remains.
The folders issue298/  and res/ in test case .zip should be in the same folder.
[issue298.zip](https://github.com/user-attachments/files/17186333/issue298.zip)

fix: Strange behavior of OnTouched #298

---

config.go
physic.go
sprite.go
tutorial/05-Animation/assets/sprites/Bullet/index.json
tutorial/05-Animation/assets/sprites/SmallEnemy/index.json

Set trigger's layer and mask to 1 by default  to maintain the same behavior as in spx1.0.
test:
```
cd tutorial/05-Animation
spx run .
```

Set trigger's layer and mask to 1 by default issue#349

---

gdspx.go

fix issue: https://github.com/goplus/spx/issues/387
Align the SPX1 position calculation algorithm: the starting point for… the `spx` image is the top left corner, while the starting point for the `gdspx` image is the center.
test project: 
[10-WebTestProj.zip](https://github.com/user-attachments/files/17712216/10-WebTestProj.zip)
before :
after this pr:

Fix sprite render offset  issue#387

---

gdspx.go

fix: https://github.com/goplus/spx/issues/397
Apply sprite's  scale to collider
test project :[10-WebTestProj.zip](https://github.com/user-attachments/files/17712325/10-WebTestProj.zip)
before:
current:

Apply sprite's  scale to collider

---

cmd/spx/main.go
cmd/spx/template/game.js
cmd/spx/template/runner.html

Add WASM cache to speed up game loading, especially in poor network conditions. 
If the engine code hasn't changed, there's no need to redownload the WASM (across projects)

Add WASM cache to speed up game loading

---

gdspx.go
sprite.go

test project: ./test/Measure
fix: 
- https://github.com/goplus/spx/issues/430
- https://github.com/goplus/spx/issues/428
- https://github.com/goplus/spx/issues/432

Fix sprite rotation, keep same with spx1

---

game.go

fix: 
- https://github.com/goplus/spx/issues/433
Make sure the window is initialized before game objects, as some objects rely on the window's size (eg: Measure)

Make sure the window is initialized before game objects, as some objects rely on the window's size (eg: Measure)

---

gdspx.go
internal/engine/sync.go

fix: 
- https://github.com/goplus/spx/issues/429
- Add coord system convert function: World <=>Screen
- Apply camera's offset to gMouseX,gMouseY

Fix the mouse position error when camera move

---

audio.go
config.go
game.go

- https://github.com/goplus/spx/issues/343
[16-BGM.zip](https://github.com/user-attachments/files/17829120/16-BGM.zip)
```
{
"bgm":"bgm",
"zorder": [
"Bullet"
]
}
```
```go
onStart => {
println "onStart"
wait 1
play "bgm", {Music:true, Action: PlayPause}
println "PlayPause"
wait 1
play "bgm", {Music:true, Action: PlayResume}
println "PlayResume"
wait 1
play "bgm", {Music:true, Action: PlayStop}
println "PlayStop"
wait 3
play "bgm", {Music:true, Action: PlayRewind}
println "PlayRewind"
}
```
https://github.com/user-attachments/assets/db45ef39-3a4b-4735-9d5f-c0fc48e6611c

Add music api

---

gdspx.go

Fix spite's pivot

---

game.go

fix: https://github.com/goplus/spx/issues/445
test project:[game.zip](https://github.com/user-attachments/files/17844750/game.zip)
before:
after:

Support backdrop mode : `fillCut`, `fillRatio`  TODO `repeat`

---

cmd/spx/template/project/.builds/web/game.js
cmd/spx/template/project/.builds/web/index.html
cmd/spx/template/project/.builds/web/runner.html

Simplify web editor api: only keep `start & stop`
Fix: https://github.com/goplus/spx/issues/452
```js
window.startGame = async (buffer, assetURLs = null) => {}
window.stopGame = async () => {}
```

Simplify web editor api

---

event.go
game.go
gdspx.go
internal/audiorecord/audiorecord_nojs.go
internal/coroutine/coro.go
internal/coroutine/queue.go
internal/engine/coro.go
internal/engine/engine.go
internal/engine/sync.gen.go
internal/engine/sync.go
internal/time/time.go
internal/tools/tool.go
quote.go
say.go
sprite.go
tick.go

Add the feature `WaitForNextFrame`, which can make the game visuals smoother.  https://github.com/goplus/spx/issues/443
The current implementation ensures that all coroutines complete execution for the current frame and enter a waiting state, thereby avoiding bugs where some sprite logic is not executed or only partially executed in a rendering frame.
The code style will have slight changes. Please see the example code below for details.
before:
```go
wait 0.05
changeYpos -10
```
after:
```go
delta := wait
changeYpos -200 * delta
```
or
```go
wait
changeYpos -200 * deltaTime
```
before: [05-Animation.zip](https://github.com/user-attachments/files/17944971/05-Animation.zip)
https://github.com/user-attachments/assets/768ea7c2-4061-426d-bc3b-2d5e8290acc6
after: …

Add feature:`wait for next frame`

---

gdspx.go
internal/coroutine/coro.go
internal/engine/proxy.go
internal/time/time.go
sprite.go
tutorial/02-Dragon/Dragon.spx

1. Use semaphores to optimize the main loop, significantly increasing the number of times the main thread function can be called per frame （700 -> 30000）
2. When the sprite's position is dirty, synchronize the sprite's transform info with the engine to ensure the collision system works correctly
Fix: https://github.com/goplus/spx/issues/421
https://github.com/user-attachments/assets/8e7f54e2-c71a-43d2-a024-995781954c2a

Use semaphores to optimize the main loop

---

camera.go
event.go
game.go
monitor.go
spbase.go
sprite.go
widget.go

- Introduce `SpriteName`, `SpriteCostumeName`, `SpriteAnimationName`, `SoundName`, `BackdropName`, `WidgetName`.
- Prefer func overloading over using `interface{}` or variadic params as optional params.

refactor: prefer typed params for API funcs

---

game.go
sprite.go

This is a workaround for #465.
---

refactor: reorder func overloads

---

monitor.go

When SPX runs in a browser with tag `canvas`, it panics if the label or value for the `Monitor` widget is an empty string. This occurs because the text-rendering operation by [canvas](https://github.com/goplus/canvas/blob/7e376755f874742425c54583cdc1cc579259d3f0/gc_js.go#L259) fails with empty content. This PR prevents such failures by checking for non-empty text content.
Example project: [issue-1287.zip](https://github.com/user-attachments/files/18668696/issue-1287.zip)
Related Builder issue: https://github.com/goplus/builder/issues/1287
Panic log:
```
panic: JavaScript error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
goroutine 12 [running]:
syscall/js.Value.Call({{}, 0x7ff8000100000192, 0x4646200}, {0x200ee3, 0xc}, {0x25276b8, 0x4, 0x4}) …
```

Fix error when drawing empty text

---

internal/coroutine/coro.go

Replaced panic/recover based abort mechanism with `runtime.Goexit` to preserve stack traces for user code panics, simplify error handling logic, and leverage standard Go runtime mechanism for goroutine abort.

refactor(internal/coroutine): use `runtime.Goexit` for aborting coroutines

---

internal/coroutine/coro.go

refactor(internal/coroutine): remove unused `ErrAbortThread`

---

game.go

Fix the bug: avoid triggering the onClick event when the sprite is invisible

Fix the bug: avoid triggering the onClick event when the sprite is invisible

---

game.go
gdspx.go
spbase.go
sprite.go

issue: https://github.com/goplus/spx/issues/512
Support layer operation: GoBackLayers, GotoBack, GotoFront
```
git clone https://github.com/JiepengTan/spx2_test_demos demos
cd demos/FlappyCalf
spx run .
```
https://github.com/user-attachments/assets/c822d399-2548-4cba-b60d-c3c6246ba712

Support layer operation: GoBackLayers, GotoBack, GotoFront

---

game.go
input.go

The stage's onClick event should only be triggered when it is not occluded by any sprite
issue: https://github.com/goplus/spx/issues/580
test project: [match3.zip](https://github.com/user-attachments/files/19755654/match3.zip)

Fix stage's onClick event

---

game.go
internal/coroutine/coro.go

test project: [tutorial/02-Dragon](https://github.com/user-attachments/files/19833808/test.zip)
In `SPX1`, since coroutines have no concept of frames, Yield can be used to voluntarily yield execution and prevent infinite loops. 
In contrast, `SPX2` introduces the concept of frames, so Yield should be replaced with `WaitNextFrame` to achieve the same effect

Fix sched bug: to prevent frame drops, break the for loop if it runs too long and continue it in the next frame

---

game.go
internal/coroutine/coro.go
internal/engine/coro.go
internal/time/time.go

test project1: [loop.zip](https://github.com/user-attachments/files/19885541/loop.zip)
```go
import "fmt"
var myIdx int
onStart => {
setXpos(-100)
idx := 0
clone 
forever => {
say fmt.Sprintf("%d", idx)
idx++
}
}
onCloned => {
setXpos(100)
wait 1
myIdx = 0
repeat 100, => {
say fmt.Sprintf("%d", myIdx)
myIdx++
}
wait 1
repeatUntil => myIdx >= 200,=> {
say fmt.Sprintf("until %d", myIdx)
myIdx++
}
wait 1
say "clear"
wait 1
forever => {
myIdx++
println("myIdx", myIdx)
}
}
onCloned => {
waitUtil => myIdx >= 300
say fmt.Sprintf("waitUtil %d done", myIdx)
myIdx++
wait 1
say "infinite for loop"
for{
myIdx++
}
}	
```
https://github.com/user-attachments/assets/60500bf8-a5a6-49e6-97ec-fabf1fb3d59f
complex test project: https://github.com/realdream-ai/spx_demos/tree/main/14_ShenGongBao
Optimize the …

Add repeat, repeatUtil, forever, Optimize the scheduling of infinite loops

---

game.go

issue: https://github.com/goplus/spx/issues/624
Auto-scale rendering to match the window size in the web platform
before:
after:
before:
after:

Auto-scale rendering to match the window size in the web platform

---

pkg/gdspx/tools/build_engine.sh

issue: https://github.com/goplus/spx/issues/527
```sh
scons platform=web target=editor \
debug_symbols="no" \  # 不需要debug 信息
optimize=size \       # 优化选项
use_volk=no \         # 不使用Vulkan
deprecated=no \       # 废弃的API
minizip=no  \         # 用不到zip
openxr=false \        # 不需要 vr ar 之类的
vulkan=false \        # 关闭Vulkan
graphite=false \      # 2D 编辑器 不需要
module_godot_physics_2d_enabled="yes" \  # 项目用到了2D物理模块
disable_3d_physics=true \                # 3D 物理模块不需要，(3D也不需要，但是Editor 有依赖不能移除)
disable_navigation=true \                # 不需要导航模块
module_msdfgen_enabled=false \           # SDF generator 用不到
module_text_server_adv_enabled=false \   # 字体高级特性 适配阿拉伯等国家，用不到
module_text_server_fb_enabled=true \     # 字体 Fallback，不启用高级特性 就必须打开
modules_enabled_by_default="no" \        # 默认所有Module …
```

Reduce web engine size

---

cmd/igox/main.go

issue: https://github.com/goplus/spx/issues/658

Fix web can not use reflection: caused by igop.DisableImethodForReflect

---

gdspx.go
spbase.go

Issue: https://github.com/goplus/spx/issues/688
test project: [test.zip](https://github.com/user-attachments/files/20754614/test.zip)
```
var (
count int
)
onStart => {
clone 
}
onCloned => {
setSize 2
setXpos -100
}
onClick => {
if count == 0 {
say "play animation", 1
animate "animation"
} else {
say "done"
say "switch costumes", 1
setCostume "倭瓜-0A3"
wait 0.1
nextCostume
wait 0.1
nextCostume
wait 0.1
nextCostume
wait 0.1
nextCostume
wait 0.1
nextCostume
wait 0.1
nextCostume
wait 0.1
setCostume "倭瓜-0A3"
say "done"
}
count = (count + 1) % 2
}
```
https://github.com/user-attachments/assets/10ee5fba-09c8-40c5-9ca4-591b6388a139

Fix animation custume offset
